### ISSUE TITLE
Recursive process.nextTick detected / RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by henryoliver** [Two-Screen/grunt-zipstream#5]
Hi,

I just get the follow error:

(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

util.js:35
  var str = String(f).replace(formatRegExp, function(x) {
                      ^
**RangeError: Maximum call stack size exceeded**

Im using the simple configuration:

``` javascript
zip: {
            file: {
                src: [
                    '<%= yeoman.dist %>/index.html'
                ],
                dest: '<%= yeoman.dist %>/app.zip'
            }
        },
```

I just uptade the node version and its start to looping trought that error.

How can i fix that? Any idea?

Thank you!

**Comment by stephank** [comment]
This is a problem with zipstream itself. And it doesn't look like we'll be getting updates.

Best solution is probably to switch to something else, like [grunt-contrib-compress](https://github.com/gruntjs/grunt-contrib-compress).
