### ISSUE TITLE
Deprecation warnings from Node

### ISSUE THREAD

**Issue by jrimmer** [Two-Screen/grunt-zipstream#6]
Running Node v0.10.4 using zipstream v0.2.2 getting screenfuls of the following message when running a zipstream task:

```
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
```

No code to attach as using the sample in the README is enough to produce it.

**Comment by jrimmer** [comment]
May or may not be related but after receiving screenfuls of the deprecation this appears at the end:

```
util.js:35
  var str = String(f).replace(formatRegExp, function(x) {
                      ^
RangeError: Maximum call stack size exceeded
```

**Comment by stephank** [comment]
Zipstream appears to be dead, and doesn't work in Node 0.10. So grunt-zipstream won't be updated either. I will add  a notice to the repo's README.

Please use [grunt-contrib-compress](https://github.com/gruntjs/grunt-contrib-compress) instead.

**Comment by jrimmer** [comment]
Thanks for the quick update. I did end up moving to [grunt-contrib-compress](https://github.com/gruntjs/grunt-contrib-compress) as you suggest.
